// Generated by gencpp from file pi_face_tracker/KeyCommandResponse.msg
// DO NOT EDIT!


#ifndef PI_FACE_TRACKER_MESSAGE_KEYCOMMANDRESPONSE_H
#define PI_FACE_TRACKER_MESSAGE_KEYCOMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pi_face_tracker
{
template <class ContainerAllocator>
struct KeyCommandResponse_
{
  typedef KeyCommandResponse_<ContainerAllocator> Type;

  KeyCommandResponse_()
    {
    }
  KeyCommandResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct KeyCommandResponse_

typedef ::pi_face_tracker::KeyCommandResponse_<std::allocator<void> > KeyCommandResponse;

typedef boost::shared_ptr< ::pi_face_tracker::KeyCommandResponse > KeyCommandResponsePtr;
typedef boost::shared_ptr< ::pi_face_tracker::KeyCommandResponse const> KeyCommandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pi_face_tracker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'pi_face_tracker': ['/home/icog-labs/hansonrobotics/HEAD/src/vision/pi_vision/pi_face_tracker/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pi_face_tracker/KeyCommandResponse";
  }

  static const char* value(const ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KeyCommandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pi_face_tracker::KeyCommandResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PI_FACE_TRACKER_MESSAGE_KEYCOMMANDRESPONSE_H
