// Generated by gencpp from file pi_face_tracker/KeyCommand.msg
// DO NOT EDIT!


#ifndef PI_FACE_TRACKER_MESSAGE_KEYCOMMAND_H
#define PI_FACE_TRACKER_MESSAGE_KEYCOMMAND_H

#include <ros/service_traits.h>


#include <pi_face_tracker/KeyCommandRequest.h>
#include <pi_face_tracker/KeyCommandResponse.h>


namespace pi_face_tracker
{

struct KeyCommand
{

typedef KeyCommandRequest Request;
typedef KeyCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KeyCommand
} // namespace pi_face_tracker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pi_face_tracker::KeyCommand > {
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::pi_face_tracker::KeyCommand&) { return value(); }
};

template<>
struct DataType< ::pi_face_tracker::KeyCommand > {
  static const char* value()
  {
    return "pi_face_tracker/KeyCommand";
  }

  static const char* value(const ::pi_face_tracker::KeyCommand&) { return value(); }
};


// service_traits::MD5Sum< ::pi_face_tracker::KeyCommandRequest> should match 
// service_traits::MD5Sum< ::pi_face_tracker::KeyCommand > 
template<>
struct MD5Sum< ::pi_face_tracker::KeyCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pi_face_tracker::KeyCommand >::value();
  }
  static const char* value(const ::pi_face_tracker::KeyCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pi_face_tracker::KeyCommandRequest> should match 
// service_traits::DataType< ::pi_face_tracker::KeyCommand > 
template<>
struct DataType< ::pi_face_tracker::KeyCommandRequest>
{
  static const char* value()
  {
    return DataType< ::pi_face_tracker::KeyCommand >::value();
  }
  static const char* value(const ::pi_face_tracker::KeyCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pi_face_tracker::KeyCommandResponse> should match 
// service_traits::MD5Sum< ::pi_face_tracker::KeyCommand > 
template<>
struct MD5Sum< ::pi_face_tracker::KeyCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pi_face_tracker::KeyCommand >::value();
  }
  static const char* value(const ::pi_face_tracker::KeyCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pi_face_tracker::KeyCommandResponse> should match 
// service_traits::DataType< ::pi_face_tracker::KeyCommand > 
template<>
struct DataType< ::pi_face_tracker::KeyCommandResponse>
{
  static const char* value()
  {
    return DataType< ::pi_face_tracker::KeyCommand >::value();
  }
  static const char* value(const ::pi_face_tracker::KeyCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PI_FACE_TRACKER_MESSAGE_KEYCOMMAND_H
