// Generated by gencpp from file pi_face_tracker/SetROI.msg
// DO NOT EDIT!


#ifndef PI_FACE_TRACKER_MESSAGE_SETROI_H
#define PI_FACE_TRACKER_MESSAGE_SETROI_H

#include <ros/service_traits.h>


#include <pi_face_tracker/SetROIRequest.h>
#include <pi_face_tracker/SetROIResponse.h>


namespace pi_face_tracker
{

struct SetROI
{

typedef SetROIRequest Request;
typedef SetROIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetROI
} // namespace pi_face_tracker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pi_face_tracker::SetROI > {
  static const char* value()
  {
    return "9586986cb2458d45fdbda6087252affd";
  }

  static const char* value(const ::pi_face_tracker::SetROI&) { return value(); }
};

template<>
struct DataType< ::pi_face_tracker::SetROI > {
  static const char* value()
  {
    return "pi_face_tracker/SetROI";
  }

  static const char* value(const ::pi_face_tracker::SetROI&) { return value(); }
};


// service_traits::MD5Sum< ::pi_face_tracker::SetROIRequest> should match 
// service_traits::MD5Sum< ::pi_face_tracker::SetROI > 
template<>
struct MD5Sum< ::pi_face_tracker::SetROIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pi_face_tracker::SetROI >::value();
  }
  static const char* value(const ::pi_face_tracker::SetROIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pi_face_tracker::SetROIRequest> should match 
// service_traits::DataType< ::pi_face_tracker::SetROI > 
template<>
struct DataType< ::pi_face_tracker::SetROIRequest>
{
  static const char* value()
  {
    return DataType< ::pi_face_tracker::SetROI >::value();
  }
  static const char* value(const ::pi_face_tracker::SetROIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pi_face_tracker::SetROIResponse> should match 
// service_traits::MD5Sum< ::pi_face_tracker::SetROI > 
template<>
struct MD5Sum< ::pi_face_tracker::SetROIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pi_face_tracker::SetROI >::value();
  }
  static const char* value(const ::pi_face_tracker::SetROIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pi_face_tracker::SetROIResponse> should match 
// service_traits::DataType< ::pi_face_tracker::SetROI > 
template<>
struct DataType< ::pi_face_tracker::SetROIResponse>
{
  static const char* value()
  {
    return DataType< ::pi_face_tracker::SetROI >::value();
  }
  static const char* value(const ::pi_face_tracker::SetROIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PI_FACE_TRACKER_MESSAGE_SETROI_H
