# Run with: sudo docker run --privileged -v /dev:/dev-host -p 8000:8000 -p 9090:9090 -it gaboose/hanson-dmitry-demo

FROM opencog/ros-indigo-dev
MAINTAINER Gabrielius Mickevicius "gabrielius.m@gmail.com"

RUN apt-get -y update
RUN apt-get -y install python3-yaml python3-pip
RUN pip3 install rospkg catkin_pkg

RUN echo source /catkin_ws/devel/setup.bash >> /.bashrc && \
    echo -e "\e[1;34m[$SELF_NAME] catkin devel setup\.bash sourced\e[0m"

RUN echo source /.bashrc >> /.bash_profile

WORKDIR /catkin_ws/src
RUN cp /opt/ros/indigo/setup.sh /etc/profile.d/ros_indigo.sh
ENV PYTHONPATH /opt/ros/indigo/lib/python2.7/dist-packages
RUN /usr/bin/python3 /opt/ros/indigo/bin/catkin_init_workspace

#serial port for python
RUN apt-get -y install python-serial

# ROS general instalation ends here
# Install expression controller and webui

RUN apt-get install -y ros-indigo-rosbridge-server

WORKDIR /catkin_ws/src
RUN git clone https://github.com/hansonrobotics/ros_pololu_servo
RUN git clone https://github.com/hansonrobotics/pau2motors
RUN git clone https://github.com/hansonrobotics/basic_head_api
RUN git clone https://github.com/hansonrobotics/ros_motors_webui
RUN git clone https://github.com/arebgun/dynamixel_motor
RUN git clone https://github.com/hansonrobotics/docker-scripts
ENV NO_CACHE 2014-08-21-07:16
RUN git clone https://github.com/hansonrobotics/robots_config

WORKDIR /catkin_ws/src/ros_pololu_servo
RUN git checkout b032d5472133f37a0a4592fe5ce28f18737a7f0f
WORKDIR /catkin_ws/src/pau2motors
RUN git checkout b729bf6d47984bf6ff477b18445543d90679c9fe
WORKDIR /catkin_ws/src/basic_head_api
RUN git checkout 0ed32769c0b431355e071b1e4b3559aeac9c4cb9
WORKDIR /catkin_ws/src/ros_motors_webui
RUN git checkout 4993c1cb8ebd5532f544046fc17a832d31bfaeef
WORKDIR /catkin_ws/src/docker-scripts
RUN git checkout a32551636596681ef9d2db6a22c5f75eab0eff88
WORKDIR /catkin_ws/src/robots_config
RUN git checkout e02729d76394937c9d8f082f52e2e9e3ffde9ea9

WORKDIR /catkin_ws
RUN bash -l -c "/usr/bin/python3 /opt/ros/indigo/bin/catkin_make"

#rosbridge websockets
EXPOSE 9090
#Webserver
EXPOSE 8000

ENTRYPOINT bash -l -c "cd /catkin_ws/src/docker-scripts; ./dmitry.sh; bash"