# Run with: docker run --privileged -v /dev:/dev-host -p 8000:8000 -p 9090:9090 -it gaboose/hanson-arthur-demo

FROM opencog/ros-indigo-dev
MAINTAINER Gabrielius Mickevicius "gabrielius.m@gmail.com"

RUN apt-get -y update
RUN apt-get -y install python3-yaml python3-pip
RUN pip3 install rospkg catkin_pkg

RUN echo source /catkin_ws/devel/setup.bash >> /.bashrc && \
    echo -e "\e[1;34m[$SELF_NAME] catkin devel setup\.bash sourced\e[0m"

RUN echo source /.bashrc >> /.bash_profile

WORKDIR /catkin_ws/src
RUN cp /opt/ros/indigo/setup.sh /etc/profile.d/ros_indigo.sh
ENV PYTHONPATH /opt/ros/indigo/lib/python2.7/dist-packages
RUN /usr/bin/python3 /opt/ros/indigo/bin/catkin_init_workspace

#serial port for python
RUN apt-get -y install python-serial

# ROS general instalation ends here
# Install expression controller and webui

RUN apt-get install -y ros-indigo-rosbridge-server

WORKDIR /catkin_ws/src
RUN git clone https://github.com/hansonrobotics/ros_pololu_servo
RUN git clone https://github.com/hansonrobotics/pau2motors
ENV NO_CACHE 2014-08-22-19:30
RUN git clone https://github.com/hansonrobotics/basic_head_api
RUN git clone https://github.com/hansonrobotics/ros_motors_webui
RUN git clone https://github.com/arebgun/dynamixel_motor
RUN git clone https://github.com/hansonrobotics/docker-scripts
RUN git clone https://github.com/hansonrobotics/robots_config

WORKDIR /catkin_ws/src/ros_pololu_servo
RUN git checkout b032d5472133f37a0a4592fe5ce28f18737a7f0f
WORKDIR /catkin_ws/src/pau2motors
RUN git checkout b729bf6d47984bf6ff477b18445543d90679c9fe
WORKDIR /catkin_ws/src/basic_head_api
RUN git checkout 7f370012b7e66315bdaaec6bef03359ef7edcf03
WORKDIR /catkin_ws/src/ros_motors_webui
RUN git checkout ad2e16e02a69698fd77280f6cda336d86baca92d
WORKDIR /catkin_ws/src/docker-scripts
RUN git checkout d36ac9cc6fd69b29f26ac74359517a293fbd88ed
WORKDIR /catkin_ws/src/robots_config
RUN git checkout 66462ede36abbc1b67c3157bbe1bd66873c65b13

WORKDIR /catkin_ws
RUN bash -l -c "/usr/bin/python3 /opt/ros/indigo/bin/catkin_make"

#rosbridge websockets
EXPOSE 9090
#Webserver
EXPOSE 8000

ENTRYPOINT bash -l -c "cd /catkin_ws/src/docker-scripts; ./arthur.sh; bash"