// Generated by gencpp from file rt_audio_ros/AudioStream.msg
// DO NOT EDIT!


#ifndef RT_AUDIO_ROS_MESSAGE_AUDIOSTREAM_H
#define RT_AUDIO_ROS_MESSAGE_AUDIOSTREAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rt_audio_ros
{
template <class ContainerAllocator>
struct AudioStream_
{
  typedef AudioStream_<ContainerAllocator> Type;

  AudioStream_()
    : header()
    , encoding(0)
    , is_bigendian(0)
    , channels(0)
    , sample_rate(0)
    , data()  {
    }
  AudioStream_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , encoding(0)
    , is_bigendian(0)
    , channels(0)
    , sample_rate(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _encoding_type;
  _encoding_type encoding;

   typedef uint8_t _is_bigendian_type;
  _is_bigendian_type is_bigendian;

   typedef uint8_t _channels_type;
  _channels_type channels;

   typedef uint32_t _sample_rate_type;
  _sample_rate_type sample_rate;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;


    enum { SINT_8_PCM = 0u };
     enum { UINT_8_PCM = 1u };
     enum { SINT_16_PCM = 2u };
     enum { SINT_24_PCM = 3u };
     enum { SINT_32_PCM = 4u };
     enum { FLOAT_32 = 5u };
     enum { FLOAT_64 = 6u };
 

  typedef boost::shared_ptr< ::rt_audio_ros::AudioStream_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rt_audio_ros::AudioStream_<ContainerAllocator> const> ConstPtr;

}; // struct AudioStream_

typedef ::rt_audio_ros::AudioStream_<std::allocator<void> > AudioStream;

typedef boost::shared_ptr< ::rt_audio_ros::AudioStream > AudioStreamPtr;
typedef boost::shared_ptr< ::rt_audio_ros::AudioStream const> AudioStreamConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rt_audio_ros::AudioStream_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rt_audio_ros::AudioStream_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rt_audio_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rt_audio_ros': ['/home/icog-labs/hansonrobotics/HEAD/src/sound/rt_audio_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rt_audio_ros::AudioStream_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt_audio_ros::AudioStream_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_audio_ros::AudioStream_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_audio_ros::AudioStream_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_audio_ros::AudioStream_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_audio_ros::AudioStream_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rt_audio_ros::AudioStream_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9370a1d8dc6e6a70477f76a5472091f6";
  }

  static const char* value(const ::rt_audio_ros::AudioStream_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9370a1d8dc6e6a70ULL;
  static const uint64_t static_value2 = 0x477f76a5472091f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::rt_audio_ros::AudioStream_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rt_audio_ros/AudioStream";
  }

  static const char* value(const ::rt_audio_ros::AudioStream_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rt_audio_ros::AudioStream_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint8 encoding\n\
\n\
uint8 SINT_8_PCM=0\n\
uint8 UINT_8_PCM=1\n\
uint8 SINT_16_PCM=2\n\
uint8 SINT_24_PCM=3\n\
uint8 SINT_32_PCM=4\n\
uint8 FLOAT_32=5\n\
uint8 FLOAT_64=6\n\
\n\
uint8  is_bigendian\n\
uint8  channels\n\
uint32 sample_rate\n\
\n\
# interleaved channels\n\
uint8[]  data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::rt_audio_ros::AudioStream_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rt_audio_ros::AudioStream_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.encoding);
      stream.next(m.is_bigendian);
      stream.next(m.channels);
      stream.next(m.sample_rate);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AudioStream_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rt_audio_ros::AudioStream_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rt_audio_ros::AudioStream_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "encoding: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.encoding);
    s << indent << "is_bigendian: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_bigendian);
    s << indent << "channels: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.channels);
    s << indent << "sample_rate: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sample_rate);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RT_AUDIO_ROS_MESSAGE_AUDIOSTREAM_H
