(cl:defpackage manyears_msgs-msg
  (:use )
  (:export
   "<SOURCEINFO>"
   "SOURCEINFO"
   "<SOURCEINFOWITHCOVARIANCE>"
   "SOURCEINFOWITHCOVARIANCE"
   "<MANYEARSTRACKEDAUDIOSOURCE>"
   "MANYEARSTRACKEDAUDIOSOURCE"
  ))

