(cl:defpackage basic_head_api-srv
  (:use )
  (:export
   "VALIDFACEEXPRS"
   "<VALIDFACEEXPRS-REQUEST>"
   "VALIDFACEEXPRS-REQUEST"
   "<VALIDFACEEXPRS-RESPONSE>"
   "VALIDFACEEXPRS-RESPONSE"
   "ANIMATIONLENGTH"
   "<ANIMATIONLENGTH-REQUEST>"
   "ANIMATIONLENGTH-REQUEST"
   "<ANIMATIONLENGTH-RESPONSE>"
   "ANIMATIONLENGTH-RESPONSE"
  ))

