// Generated by gencpp from file basic_head_api/AnimationLengthRequest.msg
// DO NOT EDIT!


#ifndef BASIC_HEAD_API_MESSAGE_ANIMATIONLENGTHREQUEST_H
#define BASIC_HEAD_API_MESSAGE_ANIMATIONLENGTHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace basic_head_api
{
template <class ContainerAllocator>
struct AnimationLengthRequest_
{
  typedef AnimationLengthRequest_<ContainerAllocator> Type;

  AnimationLengthRequest_()
    : name()  {
    }
  AnimationLengthRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;




  typedef boost::shared_ptr< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AnimationLengthRequest_

typedef ::basic_head_api::AnimationLengthRequest_<std::allocator<void> > AnimationLengthRequest;

typedef boost::shared_ptr< ::basic_head_api::AnimationLengthRequest > AnimationLengthRequestPtr;
typedef boost::shared_ptr< ::basic_head_api::AnimationLengthRequest const> AnimationLengthRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace basic_head_api

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'basic_head_api': ['/home/icog-labs/hansonrobotics/HEAD/src/hardware/basic_head_api/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::basic_head_api::AnimationLengthRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "basic_head_api/AnimationLengthRequest";
  }

  static const char* value(const ::basic_head_api::AnimationLengthRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
";
  }

  static const char* value(const ::basic_head_api::AnimationLengthRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnimationLengthRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::basic_head_api::AnimationLengthRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::basic_head_api::AnimationLengthRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASIC_HEAD_API_MESSAGE_ANIMATIONLENGTHREQUEST_H
