// Generated by gencpp from file basic_head_api/ValidFaceExprs.msg
// DO NOT EDIT!


#ifndef BASIC_HEAD_API_MESSAGE_VALIDFACEEXPRS_H
#define BASIC_HEAD_API_MESSAGE_VALIDFACEEXPRS_H

#include <ros/service_traits.h>


#include <basic_head_api/ValidFaceExprsRequest.h>
#include <basic_head_api/ValidFaceExprsResponse.h>


namespace basic_head_api
{

struct ValidFaceExprs
{

typedef ValidFaceExprsRequest Request;
typedef ValidFaceExprsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ValidFaceExprs
} // namespace basic_head_api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::basic_head_api::ValidFaceExprs > {
  static const char* value()
  {
    return "961110ff326afbad135f5b318e4e8821";
  }

  static const char* value(const ::basic_head_api::ValidFaceExprs&) { return value(); }
};

template<>
struct DataType< ::basic_head_api::ValidFaceExprs > {
  static const char* value()
  {
    return "basic_head_api/ValidFaceExprs";
  }

  static const char* value(const ::basic_head_api::ValidFaceExprs&) { return value(); }
};


// service_traits::MD5Sum< ::basic_head_api::ValidFaceExprsRequest> should match 
// service_traits::MD5Sum< ::basic_head_api::ValidFaceExprs > 
template<>
struct MD5Sum< ::basic_head_api::ValidFaceExprsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::basic_head_api::ValidFaceExprs >::value();
  }
  static const char* value(const ::basic_head_api::ValidFaceExprsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::basic_head_api::ValidFaceExprsRequest> should match 
// service_traits::DataType< ::basic_head_api::ValidFaceExprs > 
template<>
struct DataType< ::basic_head_api::ValidFaceExprsRequest>
{
  static const char* value()
  {
    return DataType< ::basic_head_api::ValidFaceExprs >::value();
  }
  static const char* value(const ::basic_head_api::ValidFaceExprsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::basic_head_api::ValidFaceExprsResponse> should match 
// service_traits::MD5Sum< ::basic_head_api::ValidFaceExprs > 
template<>
struct MD5Sum< ::basic_head_api::ValidFaceExprsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::basic_head_api::ValidFaceExprs >::value();
  }
  static const char* value(const ::basic_head_api::ValidFaceExprsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::basic_head_api::ValidFaceExprsResponse> should match 
// service_traits::DataType< ::basic_head_api::ValidFaceExprs > 
template<>
struct DataType< ::basic_head_api::ValidFaceExprsResponse>
{
  static const char* value()
  {
    return DataType< ::basic_head_api::ValidFaceExprs >::value();
  }
  static const char* value(const ::basic_head_api::ValidFaceExprsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASIC_HEAD_API_MESSAGE_VALIDFACEEXPRS_H
