// Generated by gencpp from file blender_api_msgs/GetAnimationLength.msg
// DO NOT EDIT!


#ifndef BLENDER_API_MSGS_MESSAGE_GETANIMATIONLENGTH_H
#define BLENDER_API_MSGS_MESSAGE_GETANIMATIONLENGTH_H

#include <ros/service_traits.h>


#include <blender_api_msgs/GetAnimationLengthRequest.h>
#include <blender_api_msgs/GetAnimationLengthResponse.h>


namespace blender_api_msgs
{

struct GetAnimationLength
{

typedef GetAnimationLengthRequest Request;
typedef GetAnimationLengthResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAnimationLength
} // namespace blender_api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::blender_api_msgs::GetAnimationLength > {
  static const char* value()
  {
    return "fe4f383317a23749366d3cd09901e844";
  }

  static const char* value(const ::blender_api_msgs::GetAnimationLength&) { return value(); }
};

template<>
struct DataType< ::blender_api_msgs::GetAnimationLength > {
  static const char* value()
  {
    return "blender_api_msgs/GetAnimationLength";
  }

  static const char* value(const ::blender_api_msgs::GetAnimationLength&) { return value(); }
};


// service_traits::MD5Sum< ::blender_api_msgs::GetAnimationLengthRequest> should match 
// service_traits::MD5Sum< ::blender_api_msgs::GetAnimationLength > 
template<>
struct MD5Sum< ::blender_api_msgs::GetAnimationLengthRequest>
{
  static const char* value()
  {
    return MD5Sum< ::blender_api_msgs::GetAnimationLength >::value();
  }
  static const char* value(const ::blender_api_msgs::GetAnimationLengthRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::blender_api_msgs::GetAnimationLengthRequest> should match 
// service_traits::DataType< ::blender_api_msgs::GetAnimationLength > 
template<>
struct DataType< ::blender_api_msgs::GetAnimationLengthRequest>
{
  static const char* value()
  {
    return DataType< ::blender_api_msgs::GetAnimationLength >::value();
  }
  static const char* value(const ::blender_api_msgs::GetAnimationLengthRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::blender_api_msgs::GetAnimationLengthResponse> should match 
// service_traits::MD5Sum< ::blender_api_msgs::GetAnimationLength > 
template<>
struct MD5Sum< ::blender_api_msgs::GetAnimationLengthResponse>
{
  static const char* value()
  {
    return MD5Sum< ::blender_api_msgs::GetAnimationLength >::value();
  }
  static const char* value(const ::blender_api_msgs::GetAnimationLengthResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::blender_api_msgs::GetAnimationLengthResponse> should match 
// service_traits::DataType< ::blender_api_msgs::GetAnimationLength > 
template<>
struct DataType< ::blender_api_msgs::GetAnimationLengthResponse>
{
  static const char* value()
  {
    return DataType< ::blender_api_msgs::GetAnimationLength >::value();
  }
  static const char* value(const ::blender_api_msgs::GetAnimationLengthResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BLENDER_API_MSGS_MESSAGE_GETANIMATIONLENGTH_H
