// Generated by gencpp from file blender_api_msgs/SetParam.msg
// DO NOT EDIT!


#ifndef BLENDER_API_MSGS_MESSAGE_SETPARAM_H
#define BLENDER_API_MSGS_MESSAGE_SETPARAM_H

#include <ros/service_traits.h>


#include <blender_api_msgs/SetParamRequest.h>
#include <blender_api_msgs/SetParamResponse.h>


namespace blender_api_msgs
{

struct SetParam
{

typedef SetParamRequest Request;
typedef SetParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetParam
} // namespace blender_api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::blender_api_msgs::SetParam > {
  static const char* value()
  {
    return "83f699e23d42fd7b595d420a680b1827";
  }

  static const char* value(const ::blender_api_msgs::SetParam&) { return value(); }
};

template<>
struct DataType< ::blender_api_msgs::SetParam > {
  static const char* value()
  {
    return "blender_api_msgs/SetParam";
  }

  static const char* value(const ::blender_api_msgs::SetParam&) { return value(); }
};


// service_traits::MD5Sum< ::blender_api_msgs::SetParamRequest> should match 
// service_traits::MD5Sum< ::blender_api_msgs::SetParam > 
template<>
struct MD5Sum< ::blender_api_msgs::SetParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::blender_api_msgs::SetParam >::value();
  }
  static const char* value(const ::blender_api_msgs::SetParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::blender_api_msgs::SetParamRequest> should match 
// service_traits::DataType< ::blender_api_msgs::SetParam > 
template<>
struct DataType< ::blender_api_msgs::SetParamRequest>
{
  static const char* value()
  {
    return DataType< ::blender_api_msgs::SetParam >::value();
  }
  static const char* value(const ::blender_api_msgs::SetParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::blender_api_msgs::SetParamResponse> should match 
// service_traits::MD5Sum< ::blender_api_msgs::SetParam > 
template<>
struct MD5Sum< ::blender_api_msgs::SetParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::blender_api_msgs::SetParam >::value();
  }
  static const char* value(const ::blender_api_msgs::SetParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::blender_api_msgs::SetParamResponse> should match 
// service_traits::DataType< ::blender_api_msgs::SetParam > 
template<>
struct DataType< ::blender_api_msgs::SetParamResponse>
{
  static const char* value()
  {
    return DataType< ::blender_api_msgs::SetParam >::value();
  }
  static const char* value(const ::blender_api_msgs::SetParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BLENDER_API_MSGS_MESSAGE_SETPARAM_H
