// Generated by gencpp from file blender_api_msgs/SomaStates.msg
// DO NOT EDIT!


#ifndef BLENDER_API_MSGS_MESSAGE_SOMASTATES_H
#define BLENDER_API_MSGS_MESSAGE_SOMASTATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <blender_api_msgs/SomaState.h>

namespace blender_api_msgs
{
template <class ContainerAllocator>
struct SomaStates_
{
  typedef SomaStates_<ContainerAllocator> Type;

  SomaStates_()
    : data()  {
    }
  SomaStates_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::blender_api_msgs::SomaState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::blender_api_msgs::SomaState_<ContainerAllocator> >::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::blender_api_msgs::SomaStates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blender_api_msgs::SomaStates_<ContainerAllocator> const> ConstPtr;

}; // struct SomaStates_

typedef ::blender_api_msgs::SomaStates_<std::allocator<void> > SomaStates;

typedef boost::shared_ptr< ::blender_api_msgs::SomaStates > SomaStatesPtr;
typedef boost::shared_ptr< ::blender_api_msgs::SomaStates const> SomaStatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blender_api_msgs::SomaStates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blender_api_msgs::SomaStates_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace blender_api_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'blender_api_msgs': ['/home/icog-labs/hansonrobotics/HEAD/src/blender_api_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::blender_api_msgs::SomaStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blender_api_msgs::SomaStates_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blender_api_msgs::SomaStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blender_api_msgs::SomaStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blender_api_msgs::SomaStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blender_api_msgs::SomaStates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blender_api_msgs::SomaStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1951e17e32b03a8c08e010b7ed135424";
  }

  static const char* value(const ::blender_api_msgs::SomaStates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1951e17e32b03a8cULL;
  static const uint64_t static_value2 = 0x08e010b7ed135424ULL;
};

template<class ContainerAllocator>
struct DataType< ::blender_api_msgs::SomaStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blender_api_msgs/SomaStates";
  }

  static const char* value(const ::blender_api_msgs::SomaStates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blender_api_msgs::SomaStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SomaState[] data\n\
\n\
================================================================================\n\
MSG: blender_api_msgs/SomaState\n\
string name\n\
float32 magnitude\n\
float32 rate\n\
duration ease_in\n\
";
  }

  static const char* value(const ::blender_api_msgs::SomaStates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blender_api_msgs::SomaStates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SomaStates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blender_api_msgs::SomaStates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blender_api_msgs::SomaStates_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::blender_api_msgs::SomaState_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLENDER_API_MSGS_MESSAGE_SOMASTATES_H
