// Generated by gencpp from file blender_api_msgs/Viseme.msg
// DO NOT EDIT!


#ifndef BLENDER_API_MSGS_MESSAGE_VISEME_H
#define BLENDER_API_MSGS_MESSAGE_VISEME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace blender_api_msgs
{
template <class ContainerAllocator>
struct Viseme_
{
  typedef Viseme_<ContainerAllocator> Type;

  Viseme_()
    : name()
    , start()
    , duration()
    , rampin(0.0)
    , rampout(0.0)
    , magnitude(0.0)  {
    }
  Viseme_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , start()
    , duration()
    , rampin(0.0)
    , rampout(0.0)
    , magnitude(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef ros::Time _start_type;
  _start_type start;

   typedef ros::Duration _duration_type;
  _duration_type duration;

   typedef float _rampin_type;
  _rampin_type rampin;

   typedef float _rampout_type;
  _rampout_type rampout;

   typedef float _magnitude_type;
  _magnitude_type magnitude;




  typedef boost::shared_ptr< ::blender_api_msgs::Viseme_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blender_api_msgs::Viseme_<ContainerAllocator> const> ConstPtr;

}; // struct Viseme_

typedef ::blender_api_msgs::Viseme_<std::allocator<void> > Viseme;

typedef boost::shared_ptr< ::blender_api_msgs::Viseme > VisemePtr;
typedef boost::shared_ptr< ::blender_api_msgs::Viseme const> VisemeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blender_api_msgs::Viseme_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blender_api_msgs::Viseme_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace blender_api_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'blender_api_msgs': ['/home/icog-labs/hansonrobotics/HEAD/src/blender_api_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::blender_api_msgs::Viseme_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blender_api_msgs::Viseme_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blender_api_msgs::Viseme_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blender_api_msgs::Viseme_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blender_api_msgs::Viseme_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blender_api_msgs::Viseme_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blender_api_msgs::Viseme_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d32d126f54c4095d488da702ed7cd41d";
  }

  static const char* value(const ::blender_api_msgs::Viseme_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd32d126f54c4095dULL;
  static const uint64_t static_value2 = 0x488da702ed7cd41dULL;
};

template<class ContainerAllocator>
struct DataType< ::blender_api_msgs::Viseme_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blender_api_msgs/Viseme";
  }

  static const char* value(const ::blender_api_msgs::Viseme_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blender_api_msgs::Viseme_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
time start\n\
duration duration\n\
float32 rampin\n\
float32 rampout\n\
float32 magnitude\n\
";
  }

  static const char* value(const ::blender_api_msgs::Viseme_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blender_api_msgs::Viseme_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.start);
      stream.next(m.duration);
      stream.next(m.rampin);
      stream.next(m.rampout);
      stream.next(m.magnitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Viseme_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blender_api_msgs::Viseme_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blender_api_msgs::Viseme_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "start: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.start);
    s << indent << "duration: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.duration);
    s << indent << "rampin: ";
    Printer<float>::stream(s, indent + "  ", v.rampin);
    s << indent << "rampout: ";
    Printer<float>::stream(s, indent + "  ", v.rampout);
    s << indent << "magnitude: ";
    Printer<float>::stream(s, indent + "  ", v.magnitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLENDER_API_MSGS_MESSAGE_VISEME_H
