// Generated by gencpp from file cmt_tracker_msgs/Clear.msg
// DO NOT EDIT!


#ifndef CMT_TRACKER_MSGS_MESSAGE_CLEAR_H
#define CMT_TRACKER_MSGS_MESSAGE_CLEAR_H

#include <ros/service_traits.h>


#include <cmt_tracker_msgs/ClearRequest.h>
#include <cmt_tracker_msgs/ClearResponse.h>


namespace cmt_tracker_msgs
{

struct Clear
{

typedef ClearRequest Request;
typedef ClearResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Clear
} // namespace cmt_tracker_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cmt_tracker_msgs::Clear > {
  static const char* value()
  {
    return "e19ee16a20ef206251e0359e9ec07ab5";
  }

  static const char* value(const ::cmt_tracker_msgs::Clear&) { return value(); }
};

template<>
struct DataType< ::cmt_tracker_msgs::Clear > {
  static const char* value()
  {
    return "cmt_tracker_msgs/Clear";
  }

  static const char* value(const ::cmt_tracker_msgs::Clear&) { return value(); }
};


// service_traits::MD5Sum< ::cmt_tracker_msgs::ClearRequest> should match 
// service_traits::MD5Sum< ::cmt_tracker_msgs::Clear > 
template<>
struct MD5Sum< ::cmt_tracker_msgs::ClearRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cmt_tracker_msgs::Clear >::value();
  }
  static const char* value(const ::cmt_tracker_msgs::ClearRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cmt_tracker_msgs::ClearRequest> should match 
// service_traits::DataType< ::cmt_tracker_msgs::Clear > 
template<>
struct DataType< ::cmt_tracker_msgs::ClearRequest>
{
  static const char* value()
  {
    return DataType< ::cmt_tracker_msgs::Clear >::value();
  }
  static const char* value(const ::cmt_tracker_msgs::ClearRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cmt_tracker_msgs::ClearResponse> should match 
// service_traits::MD5Sum< ::cmt_tracker_msgs::Clear > 
template<>
struct MD5Sum< ::cmt_tracker_msgs::ClearResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cmt_tracker_msgs::Clear >::value();
  }
  static const char* value(const ::cmt_tracker_msgs::ClearResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cmt_tracker_msgs::ClearResponse> should match 
// service_traits::DataType< ::cmt_tracker_msgs::Clear > 
template<>
struct DataType< ::cmt_tracker_msgs::ClearResponse>
{
  static const char* value()
  {
    return DataType< ::cmt_tracker_msgs::Clear >::value();
  }
  static const char* value(const ::cmt_tracker_msgs::ClearResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CMT_TRACKER_MSGS_MESSAGE_CLEAR_H
