// Generated by gencpp from file cmt_tracker_msgs/ClearResponse.msg
// DO NOT EDIT!


#ifndef CMT_TRACKER_MSGS_MESSAGE_CLEARRESPONSE_H
#define CMT_TRACKER_MSGS_MESSAGE_CLEARRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cmt_tracker_msgs
{
template <class ContainerAllocator>
struct ClearResponse_
{
  typedef ClearResponse_<ContainerAllocator> Type;

  ClearResponse_()
    : cleared(false)  {
    }
  ClearResponse_(const ContainerAllocator& _alloc)
    : cleared(false)  {
  (void)_alloc;
    }



   typedef uint8_t _cleared_type;
  _cleared_type cleared;




  typedef boost::shared_ptr< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ClearResponse_

typedef ::cmt_tracker_msgs::ClearResponse_<std::allocator<void> > ClearResponse;

typedef boost::shared_ptr< ::cmt_tracker_msgs::ClearResponse > ClearResponsePtr;
typedef boost::shared_ptr< ::cmt_tracker_msgs::ClearResponse const> ClearResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cmt_tracker_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'opencv_apps': ['/opt/ros/indigo/share/opencv_apps/cmake/../msg'], 'cmt_tracker_msgs': ['/home/icog-labs/hansonrobotics/HEAD/src/vision/cmt_tracker_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e19ee16a20ef206251e0359e9ec07ab5";
  }

  static const char* value(const ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe19ee16a20ef2062ULL;
  static const uint64_t static_value2 = 0x51e0359e9ec07ab5ULL;
};

template<class ContainerAllocator>
struct DataType< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cmt_tracker_msgs/ClearResponse";
  }

  static const char* value(const ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool cleared\n\
";
  }

  static const char* value(const ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cleared);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClearResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cmt_tracker_msgs::ClearResponse_<ContainerAllocator>& v)
  {
    s << indent << "cleared: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cleared);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CMT_TRACKER_MSGS_MESSAGE_CLEARRESPONSE_H
