// Generated by gencpp from file cmt_tracker_msgs/MergeNames.msg
// DO NOT EDIT!


#ifndef CMT_TRACKER_MSGS_MESSAGE_MERGENAMES_H
#define CMT_TRACKER_MSGS_MESSAGE_MERGENAMES_H

#include <ros/service_traits.h>


#include <cmt_tracker_msgs/MergeNamesRequest.h>
#include <cmt_tracker_msgs/MergeNamesResponse.h>


namespace cmt_tracker_msgs
{

struct MergeNames
{

typedef MergeNamesRequest Request;
typedef MergeNamesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MergeNames
} // namespace cmt_tracker_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cmt_tracker_msgs::MergeNames > {
  static const char* value()
  {
    return "856e68983edeb33a1b49afa6ff24e5ed";
  }

  static const char* value(const ::cmt_tracker_msgs::MergeNames&) { return value(); }
};

template<>
struct DataType< ::cmt_tracker_msgs::MergeNames > {
  static const char* value()
  {
    return "cmt_tracker_msgs/MergeNames";
  }

  static const char* value(const ::cmt_tracker_msgs::MergeNames&) { return value(); }
};


// service_traits::MD5Sum< ::cmt_tracker_msgs::MergeNamesRequest> should match 
// service_traits::MD5Sum< ::cmt_tracker_msgs::MergeNames > 
template<>
struct MD5Sum< ::cmt_tracker_msgs::MergeNamesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cmt_tracker_msgs::MergeNames >::value();
  }
  static const char* value(const ::cmt_tracker_msgs::MergeNamesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cmt_tracker_msgs::MergeNamesRequest> should match 
// service_traits::DataType< ::cmt_tracker_msgs::MergeNames > 
template<>
struct DataType< ::cmt_tracker_msgs::MergeNamesRequest>
{
  static const char* value()
  {
    return DataType< ::cmt_tracker_msgs::MergeNames >::value();
  }
  static const char* value(const ::cmt_tracker_msgs::MergeNamesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cmt_tracker_msgs::MergeNamesResponse> should match 
// service_traits::MD5Sum< ::cmt_tracker_msgs::MergeNames > 
template<>
struct MD5Sum< ::cmt_tracker_msgs::MergeNamesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cmt_tracker_msgs::MergeNames >::value();
  }
  static const char* value(const ::cmt_tracker_msgs::MergeNamesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cmt_tracker_msgs::MergeNamesResponse> should match 
// service_traits::DataType< ::cmt_tracker_msgs::MergeNames > 
template<>
struct DataType< ::cmt_tracker_msgs::MergeNamesResponse>
{
  static const char* value()
  {
    return DataType< ::cmt_tracker_msgs::MergeNames >::value();
  }
  static const char* value(const ::cmt_tracker_msgs::MergeNamesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CMT_TRACKER_MSGS_MESSAGE_MERGENAMES_H
