// Generated by gencpp from file cmt_tracker_msgs/TrackerNames.msg
// DO NOT EDIT!


#ifndef CMT_TRACKER_MSGS_MESSAGE_TRACKERNAMES_H
#define CMT_TRACKER_MSGS_MESSAGE_TRACKERNAMES_H

#include <ros/service_traits.h>


#include <cmt_tracker_msgs/TrackerNamesRequest.h>
#include <cmt_tracker_msgs/TrackerNamesResponse.h>


namespace cmt_tracker_msgs
{

struct TrackerNames
{

typedef TrackerNamesRequest Request;
typedef TrackerNamesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TrackerNames
} // namespace cmt_tracker_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cmt_tracker_msgs::TrackerNames > {
  static const char* value()
  {
    return "8538b023dbdc0b64738453dc45bb1b1a";
  }

  static const char* value(const ::cmt_tracker_msgs::TrackerNames&) { return value(); }
};

template<>
struct DataType< ::cmt_tracker_msgs::TrackerNames > {
  static const char* value()
  {
    return "cmt_tracker_msgs/TrackerNames";
  }

  static const char* value(const ::cmt_tracker_msgs::TrackerNames&) { return value(); }
};


// service_traits::MD5Sum< ::cmt_tracker_msgs::TrackerNamesRequest> should match 
// service_traits::MD5Sum< ::cmt_tracker_msgs::TrackerNames > 
template<>
struct MD5Sum< ::cmt_tracker_msgs::TrackerNamesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cmt_tracker_msgs::TrackerNames >::value();
  }
  static const char* value(const ::cmt_tracker_msgs::TrackerNamesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cmt_tracker_msgs::TrackerNamesRequest> should match 
// service_traits::DataType< ::cmt_tracker_msgs::TrackerNames > 
template<>
struct DataType< ::cmt_tracker_msgs::TrackerNamesRequest>
{
  static const char* value()
  {
    return DataType< ::cmt_tracker_msgs::TrackerNames >::value();
  }
  static const char* value(const ::cmt_tracker_msgs::TrackerNamesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cmt_tracker_msgs::TrackerNamesResponse> should match 
// service_traits::MD5Sum< ::cmt_tracker_msgs::TrackerNames > 
template<>
struct MD5Sum< ::cmt_tracker_msgs::TrackerNamesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cmt_tracker_msgs::TrackerNames >::value();
  }
  static const char* value(const ::cmt_tracker_msgs::TrackerNamesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cmt_tracker_msgs::TrackerNamesResponse> should match 
// service_traits::DataType< ::cmt_tracker_msgs::TrackerNames > 
template<>
struct DataType< ::cmt_tracker_msgs::TrackerNamesResponse>
{
  static const char* value()
  {
    return DataType< ::cmt_tracker_msgs::TrackerNames >::value();
  }
  static const char* value(const ::cmt_tracker_msgs::TrackerNamesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CMT_TRACKER_MSGS_MESSAGE_TRACKERNAMES_H
