// Generated by gencpp from file performances/RunRequest.msg
// DO NOT EDIT!


#ifndef PERFORMANCES_MESSAGE_RUNREQUEST_H
#define PERFORMANCES_MESSAGE_RUNREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace performances
{
template <class ContainerAllocator>
struct RunRequest_
{
  typedef RunRequest_<ContainerAllocator> Type;

  RunRequest_()
    : startTime(0.0)  {
    }
  RunRequest_(const ContainerAllocator& _alloc)
    : startTime(0.0)  {
  (void)_alloc;
    }



   typedef double _startTime_type;
  _startTime_type startTime;




  typedef boost::shared_ptr< ::performances::RunRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::performances::RunRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RunRequest_

typedef ::performances::RunRequest_<std::allocator<void> > RunRequest;

typedef boost::shared_ptr< ::performances::RunRequest > RunRequestPtr;
typedef boost::shared_ptr< ::performances::RunRequest const> RunRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::performances::RunRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::performances::RunRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace performances

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'performances': ['/home/icog-labs/hansonrobotics/HEAD/src/performances/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::performances::RunRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::performances::RunRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::performances::RunRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::performances::RunRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::performances::RunRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::performances::RunRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::performances::RunRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdd06493b159d240c59a0f367a62f772";
  }

  static const char* value(const ::performances::RunRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfdd06493b159d240ULL;
  static const uint64_t static_value2 = 0xc59a0f367a62f772ULL;
};

template<class ContainerAllocator>
struct DataType< ::performances::RunRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "performances/RunRequest";
  }

  static const char* value(const ::performances::RunRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::performances::RunRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 startTime\n\
";
  }

  static const char* value(const ::performances::RunRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::performances::RunRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.startTime);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RunRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::performances::RunRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::performances::RunRequest_<ContainerAllocator>& v)
  {
    s << indent << "startTime: ";
    Printer<double>::stream(s, indent + "  ", v.startTime);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERFORMANCES_MESSAGE_RUNREQUEST_H
