// Generated by gencpp from file performances/SpeechOnRequest.msg
// DO NOT EDIT!


#ifndef PERFORMANCES_MESSAGE_SPEECHONREQUEST_H
#define PERFORMANCES_MESSAGE_SPEECHONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace performances
{
template <class ContainerAllocator>
struct SpeechOnRequest_
{
  typedef SpeechOnRequest_<ContainerAllocator> Type;

  SpeechOnRequest_()
    : speech()  {
    }
  SpeechOnRequest_(const ContainerAllocator& _alloc)
    : speech(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _speech_type;
  _speech_type speech;




  typedef boost::shared_ptr< ::performances::SpeechOnRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::performances::SpeechOnRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechOnRequest_

typedef ::performances::SpeechOnRequest_<std::allocator<void> > SpeechOnRequest;

typedef boost::shared_ptr< ::performances::SpeechOnRequest > SpeechOnRequestPtr;
typedef boost::shared_ptr< ::performances::SpeechOnRequest const> SpeechOnRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::performances::SpeechOnRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::performances::SpeechOnRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace performances

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'performances': ['/home/icog-labs/hansonrobotics/HEAD/src/performances/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::performances::SpeechOnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::performances::SpeechOnRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::performances::SpeechOnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::performances::SpeechOnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::performances::SpeechOnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::performances::SpeechOnRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::performances::SpeechOnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f212b08e2dfacb9148fa1a62023e9ac";
  }

  static const char* value(const ::performances::SpeechOnRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f212b08e2dfacb9ULL;
  static const uint64_t static_value2 = 0x148fa1a62023e9acULL;
};

template<class ContainerAllocator>
struct DataType< ::performances::SpeechOnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "performances/SpeechOnRequest";
  }

  static const char* value(const ::performances::SpeechOnRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::performances::SpeechOnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string speech\n\
";
  }

  static const char* value(const ::performances::SpeechOnRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::performances::SpeechOnRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speech);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechOnRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::performances::SpeechOnRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::performances::SpeechOnRequest_<ContainerAllocator>& v)
  {
    s << indent << "speech: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.speech);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERFORMANCES_MESSAGE_SPEECHONREQUEST_H
