// Generated by gencpp from file tts/TTSLengthResponse.msg
// DO NOT EDIT!


#ifndef TTS_MESSAGE_TTSLENGTHRESPONSE_H
#define TTS_MESSAGE_TTSLENGTHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tts
{
template <class ContainerAllocator>
struct TTSLengthResponse_
{
  typedef TTSLengthResponse_<ContainerAllocator> Type;

  TTSLengthResponse_()
    : length(0.0)  {
    }
  TTSLengthResponse_(const ContainerAllocator& _alloc)
    : length(0.0)  {
  (void)_alloc;
    }



   typedef float _length_type;
  _length_type length;




  typedef boost::shared_ptr< ::tts::TTSLengthResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tts::TTSLengthResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TTSLengthResponse_

typedef ::tts::TTSLengthResponse_<std::allocator<void> > TTSLengthResponse;

typedef boost::shared_ptr< ::tts::TTSLengthResponse > TTSLengthResponsePtr;
typedef boost::shared_ptr< ::tts::TTSLengthResponse const> TTSLengthResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tts::TTSLengthResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tts::TTSLengthResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tts

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tts::TTSLengthResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tts::TTSLengthResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tts::TTSLengthResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tts::TTSLengthResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tts::TTSLengthResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tts::TTSLengthResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tts::TTSLengthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30516591bd33c945cbc4d8d225f8022b";
  }

  static const char* value(const ::tts::TTSLengthResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30516591bd33c945ULL;
  static const uint64_t static_value2 = 0xcbc4d8d225f8022bULL;
};

template<class ContainerAllocator>
struct DataType< ::tts::TTSLengthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tts/TTSLengthResponse";
  }

  static const char* value(const ::tts::TTSLengthResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tts::TTSLengthResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 length\n\
\n\
";
  }

  static const char* value(const ::tts::TTSLengthResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tts::TTSLengthResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.length);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TTSLengthResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tts::TTSLengthResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tts::TTSLengthResponse_<ContainerAllocator>& v)
  {
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TTS_MESSAGE_TTSLENGTHRESPONSE_H
