// Generated by gencpp from file webui/JsonResponse.msg
// DO NOT EDIT!


#ifndef WEBUI_MESSAGE_JSONRESPONSE_H
#define WEBUI_MESSAGE_JSONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace webui
{
template <class ContainerAllocator>
struct JsonResponse_
{
  typedef JsonResponse_<ContainerAllocator> Type;

  JsonResponse_()
    : success(false)
    , response()  {
    }
  JsonResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , response(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;




  typedef boost::shared_ptr< ::webui::JsonResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webui::JsonResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JsonResponse_

typedef ::webui::JsonResponse_<std::allocator<void> > JsonResponse;

typedef boost::shared_ptr< ::webui::JsonResponse > JsonResponsePtr;
typedef boost::shared_ptr< ::webui::JsonResponse const> JsonResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webui::JsonResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webui::JsonResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace webui

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::webui::JsonResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webui::JsonResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webui::JsonResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webui::JsonResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webui::JsonResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webui::JsonResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webui::JsonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "187f74b76a3c78db0f92719010b77755";
  }

  static const char* value(const ::webui::JsonResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x187f74b76a3c78dbULL;
  static const uint64_t static_value2 = 0x0f92719010b77755ULL;
};

template<class ContainerAllocator>
struct DataType< ::webui::JsonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webui/JsonResponse";
  }

  static const char* value(const ::webui::JsonResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webui::JsonResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
string response\n\
\n\
";
  }

  static const char* value(const ::webui::JsonResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webui::JsonResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JsonResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webui::JsonResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::webui::JsonResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEBUI_MESSAGE_JSONRESPONSE_H
