// Generated by gencpp from file webui/MotorStates.msg
// DO NOT EDIT!


#ifndef WEBUI_MESSAGE_MOTORSTATES_H
#define WEBUI_MESSAGE_MOTORSTATES_H

#include <ros/service_traits.h>


#include <webui/MotorStatesRequest.h>
#include <webui/MotorStatesResponse.h>


namespace webui
{

struct MotorStates
{

typedef MotorStatesRequest Request;
typedef MotorStatesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotorStates
} // namespace webui


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webui::MotorStates > {
  static const char* value()
  {
    return "6f2ab127d4c72388212187489e68122d";
  }

  static const char* value(const ::webui::MotorStates&) { return value(); }
};

template<>
struct DataType< ::webui::MotorStates > {
  static const char* value()
  {
    return "webui/MotorStates";
  }

  static const char* value(const ::webui::MotorStates&) { return value(); }
};


// service_traits::MD5Sum< ::webui::MotorStatesRequest> should match 
// service_traits::MD5Sum< ::webui::MotorStates > 
template<>
struct MD5Sum< ::webui::MotorStatesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webui::MotorStates >::value();
  }
  static const char* value(const ::webui::MotorStatesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webui::MotorStatesRequest> should match 
// service_traits::DataType< ::webui::MotorStates > 
template<>
struct DataType< ::webui::MotorStatesRequest>
{
  static const char* value()
  {
    return DataType< ::webui::MotorStates >::value();
  }
  static const char* value(const ::webui::MotorStatesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webui::MotorStatesResponse> should match 
// service_traits::MD5Sum< ::webui::MotorStates > 
template<>
struct MD5Sum< ::webui::MotorStatesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webui::MotorStates >::value();
  }
  static const char* value(const ::webui::MotorStatesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webui::MotorStatesResponse> should match 
// service_traits::DataType< ::webui::MotorStates > 
template<>
struct DataType< ::webui::MotorStatesResponse>
{
  static const char* value()
  {
    return DataType< ::webui::MotorStates >::value();
  }
  static const char* value(const ::webui::MotorStatesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBUI_MESSAGE_MOTORSTATES_H
