// Generated by gencpp from file webui/NodeDescriptionRequest.msg
// DO NOT EDIT!


#ifndef WEBUI_MESSAGE_NODEDESCRIPTIONREQUEST_H
#define WEBUI_MESSAGE_NODEDESCRIPTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace webui
{
template <class ContainerAllocator>
struct NodeDescriptionRequest_
{
  typedef NodeDescriptionRequest_<ContainerAllocator> Type;

  NodeDescriptionRequest_()
    : node()  {
    }
  NodeDescriptionRequest_(const ContainerAllocator& _alloc)
    : node(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _node_type;
  _node_type node;




  typedef boost::shared_ptr< ::webui::NodeDescriptionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webui::NodeDescriptionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NodeDescriptionRequest_

typedef ::webui::NodeDescriptionRequest_<std::allocator<void> > NodeDescriptionRequest;

typedef boost::shared_ptr< ::webui::NodeDescriptionRequest > NodeDescriptionRequestPtr;
typedef boost::shared_ptr< ::webui::NodeDescriptionRequest const> NodeDescriptionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webui::NodeDescriptionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webui::NodeDescriptionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace webui

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::webui::NodeDescriptionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webui::NodeDescriptionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webui::NodeDescriptionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webui::NodeDescriptionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webui::NodeDescriptionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webui::NodeDescriptionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webui::NodeDescriptionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a94c40e70a4b82863e6e52ec16732447";
  }

  static const char* value(const ::webui::NodeDescriptionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa94c40e70a4b8286ULL;
  static const uint64_t static_value2 = 0x3e6e52ec16732447ULL;
};

template<class ContainerAllocator>
struct DataType< ::webui::NodeDescriptionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webui/NodeDescriptionRequest";
  }

  static const char* value(const ::webui::NodeDescriptionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webui::NodeDescriptionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string node\n\
";
  }

  static const char* value(const ::webui::NodeDescriptionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webui::NodeDescriptionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NodeDescriptionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webui::NodeDescriptionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::webui::NodeDescriptionRequest_<ContainerAllocator>& v)
  {
    s << indent << "node: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.node);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEBUI_MESSAGE_NODEDESCRIPTIONREQUEST_H
