// Generated by gencpp from file webui/NodeConfigurationResponse.msg
// DO NOT EDIT!


#ifndef WEBUI_MESSAGE_NODECONFIGURATIONRESPONSE_H
#define WEBUI_MESSAGE_NODECONFIGURATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace webui
{
template <class ContainerAllocator>
struct NodeConfigurationResponse_
{
  typedef NodeConfigurationResponse_<ContainerAllocator> Type;

  NodeConfigurationResponse_()
    : configuration()  {
    }
  NodeConfigurationResponse_(const ContainerAllocator& _alloc)
    : configuration(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _configuration_type;
  _configuration_type configuration;




  typedef boost::shared_ptr< ::webui::NodeConfigurationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webui::NodeConfigurationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NodeConfigurationResponse_

typedef ::webui::NodeConfigurationResponse_<std::allocator<void> > NodeConfigurationResponse;

typedef boost::shared_ptr< ::webui::NodeConfigurationResponse > NodeConfigurationResponsePtr;
typedef boost::shared_ptr< ::webui::NodeConfigurationResponse const> NodeConfigurationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webui::NodeConfigurationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webui::NodeConfigurationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace webui

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::webui::NodeConfigurationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webui::NodeConfigurationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webui::NodeConfigurationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webui::NodeConfigurationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webui::NodeConfigurationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webui::NodeConfigurationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webui::NodeConfigurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c476281fb8327e65d0b0467ac580069";
  }

  static const char* value(const ::webui::NodeConfigurationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c476281fb8327e6ULL;
  static const uint64_t static_value2 = 0x5d0b0467ac580069ULL;
};

template<class ContainerAllocator>
struct DataType< ::webui::NodeConfigurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webui/NodeConfigurationResponse";
  }

  static const char* value(const ::webui::NodeConfigurationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webui::NodeConfigurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string configuration\n\
\n\
";
  }

  static const char* value(const ::webui::NodeConfigurationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webui::NodeConfigurationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.configuration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NodeConfigurationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webui::NodeConfigurationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::webui::NodeConfigurationResponse_<ContainerAllocator>& v)
  {
    s << indent << "configuration: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.configuration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEBUI_MESSAGE_NODECONFIGURATIONRESPONSE_H
