// Generated by gencpp from file webui/NodeDescriptionResponse.msg
// DO NOT EDIT!


#ifndef WEBUI_MESSAGE_NODEDESCRIPTIONRESPONSE_H
#define WEBUI_MESSAGE_NODEDESCRIPTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace webui
{
template <class ContainerAllocator>
struct NodeDescriptionResponse_
{
  typedef NodeDescriptionResponse_<ContainerAllocator> Type;

  NodeDescriptionResponse_()
    : description()  {
    }
  NodeDescriptionResponse_(const ContainerAllocator& _alloc)
    : description(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;




  typedef boost::shared_ptr< ::webui::NodeDescriptionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webui::NodeDescriptionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NodeDescriptionResponse_

typedef ::webui::NodeDescriptionResponse_<std::allocator<void> > NodeDescriptionResponse;

typedef boost::shared_ptr< ::webui::NodeDescriptionResponse > NodeDescriptionResponsePtr;
typedef boost::shared_ptr< ::webui::NodeDescriptionResponse const> NodeDescriptionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webui::NodeDescriptionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webui::NodeDescriptionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace webui

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::webui::NodeDescriptionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webui::NodeDescriptionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webui::NodeDescriptionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webui::NodeDescriptionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webui::NodeDescriptionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webui::NodeDescriptionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webui::NodeDescriptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56a2040e58d4fe3f4d4a0df112eea2f6";
  }

  static const char* value(const ::webui::NodeDescriptionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56a2040e58d4fe3fULL;
  static const uint64_t static_value2 = 0x4d4a0df112eea2f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::webui::NodeDescriptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webui/NodeDescriptionResponse";
  }

  static const char* value(const ::webui::NodeDescriptionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webui::NodeDescriptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string description\n\
\n\
";
  }

  static const char* value(const ::webui::NodeDescriptionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webui::NodeDescriptionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NodeDescriptionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webui::NodeDescriptionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::webui::NodeDescriptionResponse_<ContainerAllocator>& v)
  {
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEBUI_MESSAGE_NODEDESCRIPTIONRESPONSE_H
