// Generated by gencpp from file ros_nmpt_saliency/targets.msg
// DO NOT EDIT!


#ifndef ROS_NMPT_SALIENCY_MESSAGE_TARGETS_H
#define ROS_NMPT_SALIENCY_MESSAGE_TARGETS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace ros_nmpt_saliency
{
template <class ContainerAllocator>
struct targets_
{
  typedef targets_<ContainerAllocator> Type;

  targets_()
    : positions()
    , degree(0.0)  {
    }
  targets_(const ContainerAllocator& _alloc)
    : positions(_alloc)
    , degree(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _positions_type;
  _positions_type positions;

   typedef float _degree_type;
  _degree_type degree;




  typedef boost::shared_ptr< ::ros_nmpt_saliency::targets_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_nmpt_saliency::targets_<ContainerAllocator> const> ConstPtr;

}; // struct targets_

typedef ::ros_nmpt_saliency::targets_<std::allocator<void> > targets;

typedef boost::shared_ptr< ::ros_nmpt_saliency::targets > targetsPtr;
typedef boost::shared_ptr< ::ros_nmpt_saliency::targets const> targetsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_nmpt_saliency::targets_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_nmpt_saliency::targets_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_nmpt_saliency

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'ros_nmpt_saliency': ['/home/icog-labs/hansonrobotics/HEAD/src/vision/ros_nmpt_saliency/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_nmpt_saliency::targets_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_nmpt_saliency::targets_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_nmpt_saliency::targets_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_nmpt_saliency::targets_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_nmpt_saliency::targets_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_nmpt_saliency::targets_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_nmpt_saliency::targets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaf8d5353bd6068bc7a7a3420ba17cf6";
  }

  static const char* value(const ::ros_nmpt_saliency::targets_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaf8d5353bd6068bULL;
  static const uint64_t static_value2 = 0xc7a7a3420ba17cf6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_nmpt_saliency::targets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_nmpt_saliency/targets";
  }

  static const char* value(const ::ros_nmpt_saliency::targets_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_nmpt_saliency::targets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] positions\n\
float32 degree\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::ros_nmpt_saliency::targets_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_nmpt_saliency::targets_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
      stream.next(m.degree);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct targets_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_nmpt_saliency::targets_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_nmpt_saliency::targets_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.positions[i]);
    }
    s << indent << "degree: ";
    Printer<float>::stream(s, indent + "  ", v.degree);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_NMPT_SALIENCY_MESSAGE_TARGETS_H
