(cl:defpackage blender_api_msgs-srv
  (:use )
  (:export
   "GETPARAM"
   "<GETPARAM-REQUEST>"
   "GETPARAM-REQUEST"
   "<GETPARAM-RESPONSE>"
   "GETPARAM-RESPONSE"
   "GETANIMATIONLENGTH"
   "<GETANIMATIONLENGTH-REQUEST>"
   "GETANIMATIONLENGTH-REQUEST"
   "<GETANIMATIONLENGTH-RESPONSE>"
   "GETANIMATIONLENGTH-RESPONSE"
   "SETPARAM"
   "<SETPARAM-REQUEST>"
   "SETPARAM-REQUEST"
   "<SETPARAM-RESPONSE>"
   "SETPARAM-RESPONSE"
  ))

